# These are supported funding model platforms

patreon: inspiredindividuals
ko_fi: inspiredindividuals
liberapay: InspiredIndividuals
ADA: addr1q9gma46xkx4a4qrdnxxl85hqnzmgwrg2j8vvwm3vf7h3we3fxlp3k95vrt5dm85x0dq8rv7jalsre8dgyzdr69jwaqyskz6wvh
